### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xiedaibin** [kot32go/KSimpleLibrary#1]
模拟器上有这个问题，在手机上没有。
12-07 05:50:45.009 705-705/? E/AndroidRuntime: FATAL EXCEPTION: main
                                               java.lang.NullPointerException
                                                   at android.graphics.Canvas.drawArc(Canvas.java:990)
                                                   at com.kot32.ksimplelibrary.widgets.view.KLoadingView.dispatchDraw(KLoadingView.java:97)
                                                   at android.view.View.draw(View.java:13340)
                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
                                                   at android.view.View.draw(View.java:13461)
                                                   at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                   at android.view.View.draw(View.java:13342)
                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
                                                   at android.view.View.draw(View.java:13340)
                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
                                                   at android.view.View.draw(View.java:13340)
                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
                                                   at android.view.View.draw(View.java:13340)
                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
                                                   at android.view.View.draw(View.java:13461)
                                                   at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2183)
                                                   at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2258)
                                                   at android.view.ViewRootImpl.draw(ViewRootImpl.java:2153)
                                                   at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2021)
                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1832)
                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4214)
                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                                                   at android.view.Choreographer.doFrame(Choreographer.java:525)
                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                                                   at android.os.Handler.handleCallback(Handler.java:615)
                                                   at android.os.Handler.dispatchMessage(Handler.java:92)
                                                   at android.os.Looper.loop(Looper.java:137)
                                                   at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                   at java.lang.reflect.Method.invoke(Method.java:511)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by kot32go** [comment]
请问是什么模拟器呢？
