### ISSUE TITLE
构建DRAWER调用.addDrawerSubItem(R.drawable.pwd2, "评论", null, null)报错

### ISSUE THREAD

**Issue by EasonTao** [kot32go/KSimpleLibrary#3]
07-18 15:18:33.320 31340-31340/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.plantnurse.plantnurse, PID: 31340
                                                   java.lang.NullPointerException: SimpleDraweeView was not initialized!
                                                       at com.facebook.common.internal.Preconditions.checkNotNull(Preconditions.java:226)
                                                       at com.facebook.drawee.view.SimpleDraweeView.init(SimpleDraweeView.java:71)
                                                       at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:54)
                                                       at com.kot32.ksimplelibrary.widgets.drawer.KDrawerBuilder.addDrawerSubItem(KDrawerBuilder.java:310)
                                                       at com.kot32.ksimplelibrary.widgets.drawer.KDrawerBuilder.addDrawerSubItem(KDrawerBuilder.java:301)
                                                       at com.kot32.ksimplelibrary.widgets.drawer.KDrawerBuilder.addDrawerSubItem1(KDrawerBuilder.java:292)
                                                       at com.plantnurse.plantnurse.Activity.MainActivity.initView(MainActivity.java:92)
                                                       at com.kot32.ksimplelibrary.activity.e.KSimpleBaseActivity.showContentView(KSimpleBaseActivity.java:127)
                                                       at com.kot32.ksimplelibrary.activity.e.KSimpleBaseActivity.access$500(KSimpleBaseActivity.java:24)
                                                       at com.kot32.ksimplelibrary.activity.e.KSimpleBaseActivity$1.onPostExecute(KSimpleBaseActivity.java:101)
                                                       at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                       at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:145)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5835)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

改了很久也没改好，请作者帮忙看一下

**Comment by kot32go** [comment]
今晚下班了帮你看看，顺便改一下library 里面已知的bug :D
目测是没有继承KSimpleApplication 哦

**Comment by EasonTao** [comment]
恩恩  的确是这个问题 现在已经解决啦~谢谢~（竟然目测就能debug  胜过我们俩研究半天的时间）
